#!/usr/bin/env python3

import os, re

path = os.path.join(os.getcwd(), 'test.ngc')
with open(path) as f:
	raw_gcode = f.readlines()

clean_gcode = []
for line in raw_gcode:
	line = line.strip()
	if line.startswith(';'):
		continue
	if line.startswith('(') and line.endswith(')'):
		continue
	if ';' in line:
		line = line.split(';')[0]
	if '(' in line:
		line = re.sub("[\(\[].*?[\)\]]", "", line)
	clean_gcode.append(line)

for line in clean_gcode:
	print(line)



